name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Run tests
      run: |
        cd ProcessResponse
        qmake
        make
        ./test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Build
      run: |
        cd Elka-Drive-Desktop
        qmake
        make

