name: CI

on: [push]

jobs:
  integration-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init submodule
      run: git submodule update --init

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Build app
      run: |
        echo "QMake"
        qmake
        echo "make"
        make
        echo "make install"
        sudo make install
    - name: Run tests
      run: |
        ./ProcessResponse/test

  integration-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init submodule
      run: git submodule update --init

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win64_mingw73

    - name: Build app
      run: |
        qmake.exe
        mingw32-make.exe install
        mingw32-make.exe
    - name: Run tests
      run: |
        ls ProcessResponse
        echo "ls release"
        ls ProcessResponse/release
        echo "run test"
        ./ProcessResponse/release/test.exe

