name: CI

on: [push]

jobs:
#   install-qt:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Install Qt
#       uses: jurplel/install-qt-action@v2

  tests:
    runs-on: ubuntu-latest
#     needs: [install-qt]

    steps:
    - name: Run tests
#      working-directory: ${{ github.workspace }}
      run: ls -la
#       run: |
#         cd ..
#         pwd
#         ls -a
#         ls -a ..
#         cd ProcessResponse
#         qmake
#         make
#         ./test
