name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Run a multi-line script
      run: |
        cd ProcessResponse
        qmake
        make
        ./test
