name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

  tests:
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
    - name: Run tests
      run: |
        cd ProcessResponse
        qmake
        make
        ./test

  build:
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
    - name: Build
      run: |
        cd Elka-Drive-Desktop
        qmake
        make

