name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build
      run: |
        qmake
        make
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Elka-Drive-Desktop/Elka-Drive-Desktop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}