name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt
      run: |
        git clone https://code.qt.io/qt/qt5.git
        cd qt5
        git checkout 5.12
        perl init-repository
        ./configure -static
        make
    - name: Build
      run: |
        qt5/bin/qmake -config release
        make
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Elka-Drive-Desktop/Elka-Drive-Desktop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
